#!/bin/bash
# Snapclient installation script for Debian/Ubuntu-based systems

set -e

echo "==================================="
echo "Snapclient Installation Script"
echo "==================================="
echo ""

# Check if running as root
if [ "$EUID" -ne 0 ]; then 
    echo "Please run as root (use sudo)"
    exit 1
fi

# Detect OS
if [ -f /etc/os-release ]; then
    . /etc/os-release
    OS=$NAME
    VERSION=$VERSION_ID
else
    echo "Cannot detect OS. This script supports Debian/Ubuntu-based systems."
    exit 1
fi

echo "Detected OS: $OS $VERSION"
echo ""

# Update package list
echo "Updating package list..."
apt-get update

# Install snapclient
echo "Installing snapclient..."
apt-get install -y snapclient

# Ask for server IP
read -p "Enter your multiroom server IP address: " SERVER_IP

# Validate IP format (basic check)
if [[ ! $SERVER_IP =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
    echo "Invalid IP address format. Please edit /etc/default/snapclient manually."
    SERVER_IP="192.168.1.100"
fi

# Create configuration
echo "Creating configuration..."
cat > /etc/default/snapclient << EOF
# Snapclient configuration
# Generated by install script

SNAPCLIENT_OPTS="--host $SERVER_IP"

# Uncomment and adjust options as needed:
# SNAPCLIENT_OPTS="--host $SERVER_IP --latency 200"
# SNAPCLIENT_OPTS="--host $SERVER_IP --soundcard default"
# SNAPCLIENT_OPTS="--host $SERVER_IP --volume 75"
EOF

# Enable and start service
echo "Enabling and starting snapclient service..."
systemctl enable snapclient
systemctl start snapclient

# Check status
echo ""
echo "Installation complete!"
echo ""
echo "Service status:"
systemctl status snapclient --no-pager -l

echo ""
echo "==================================="
echo "Next Steps:"
echo "==================================="
echo "1. Check if client connected: sudo journalctl -u snapclient -f"
echo "2. Open web interface: http://$SERVER_IP:1780"
echo "3. Adjust volume and settings from the web interface"
echo ""
echo "Configuration file: /etc/default/snapclient"
echo "Edit it to adjust settings, then: sudo systemctl restart snapclient"
